version: 2

models:
  - name: snap_company
    columns:
      - name: snapshot_id
        tests:
          - not_null
          - unique
      - name: snapshot_run_id
        tests:
          - not_null
      - name: company_id
        tests:
          - not_null
      - name: document_version
        tests:
          - not_null
      - name: source_modified_at_utc
        tests:
          - not_null
